use TMPP_UNIVER;

select min(AUDITORIUM_CAPACITY)[Минимальная вместимость],
	max(AUDITORIUM_CAPACITY)[Максимальная вместимость],
	avg(AUDITORIUM_CAPACITY)[Средняя вместимость],
	sum(AUDITORIUM_CAPACITY)[Суммарная вместимость],
	count(*)[Количество аудиторий] from AUDITORIUM;

select AUDITORIUM_TYPE.AUDITORIUM_TYPE, min(AUDITORIUM_CAPACITY)[Минимальная вместимость],
	max(AUDITORIUM_CAPACITY)[Максимальная вместимость],
	avg(AUDITORIUM_CAPACITY)[Средняя вместимость],
	sum(AUDITORIUM_CAPACITY)[Суммарная вместимость],
	count(*)[Количество аудиторий] from AUDITORIUM inner join Auditorium_type on AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE 
	group by AUDITORIUM_TYPE.AUDITORIUM_TYPE;

SELECT  *
 FROM (select Case 
   when NOTE  between 4 and  5  then '4-5'
   when NOTE  between 6 and  7  then '6-7'
   when NOTE  between 8 and  9  then '8-9'
   else '10'
   end  [Оценки], COUNT (*) [Количество]    
FROM PROGRESS Group by Case 
   when NOTE  between 4 and  5  then '4-5'
   when NOTE  between 6 and  7  then '6-7'
   when NOTE  between 8 and  9  then '8-9'
   else '10'
   end ) as T
ORDER BY  Case [Оценки]
   when '4-5' then 4
   when '6-7' then 3
   when '8-9' then 2
   else 1
   end;

 SELECT  f.FACULTY, g.PROFESSION,
case  when g.YEAR_FIRST = 2010 then '4'
	  when g.YEAR_FIRST = 2011 then '3'
	  when g.YEAR_FIRST = 2012 then '2'
	  when g.YEAR_FIRST = 2013 then '1'
   else 'выпуск'
   end  [Курс],  
 round(avg(cast(p.NOTE as float(4))),2) [Средняя оценка]
From FACULTY f inner join GROUPS g 
            on f.FACULTY = g.FACULTY
            inner join STUDENT s  
            on g.IDGROUP = s.IDGROUP
			inner join PROGRESS p
			on s.IDSTUDENT = p.IDSTUDENT                
GROUP BY g.PROFESSION, f.FACULTY, g.YEAR_FIRST
ORDER BY [Средняя оценка] desc;


 SELECT  f.FACULTY, g.PROFESSION, p.SUBJECT,
case  when g.YEAR_FIRST = 2010 then '4'
	  when g.YEAR_FIRST = 2011 then '3'
	  when g.YEAR_FIRST = 2012 then '2'
	  when g.YEAR_FIRST = 2013 then '1'
   else 'выпуск'
   end  [Курс],  
 round(avg(cast(p.NOTE as float(4))),2) [Средняя оценка]
From FACULTY f inner join GROUPS g 
            on f.FACULTY = g.FACULTY
            inner join STUDENT s  
            on g.IDGROUP = s.IDGROUP
			inner join PROGRESS p
			on s.IDSTUDENT = p.IDSTUDENT  
where p.[SUBJECT]='БД' or p.[SUBJECT] = 'ОАиП'                
GROUP BY g.PROFESSION, f.FACULTY, g.YEAR_FIRST, p.SUBJECT
ORDER BY [Средняя оценка] desc;


SELECT GROUPS.FACULTY[Факультет],GROUPS.PROFESSION[Специальность],PROGRESS.SUBJECT[Дисциплины], 
	   ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	   FROM GROUPS INNER JOIN FACULTY ON 
	   GROUPS.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION 
	   INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
	   INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
	   WHERE GROUPS.FACULTY IN ('ИДиП')
	   GROUP BY ROLLUP (GROUPS.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT);

	   SELECT GROUPS.FACULTY[Факультет],GROUPS.PROFESSION[Специальность],PROGRESS.SUBJECT[Дисциплины], 
	   ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	   FROM GROUPS INNER JOIN FACULTY ON 
	   GROUPS.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION 
	   INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
	   INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
	   WHERE GROUPS.FACULTY IN ('ИДиП')
	   GROUP BY ROLLUP (GROUPS.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT);

SELECT GROUPS.FACULTY[Факультет],GROUPS.PROFESSION[Специальность],PROGRESS.SUBJECT[Дисциплины], 
	   ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	   FROM GROUPS INNER JOIN FACULTY ON 
	   GROUPS.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION 
	   INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
	   INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
	   WHERE GROUPS.FACULTY IN ('ИДиП')
	   GROUP BY CUBE (GROUPS.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT);

 

SELECT GROUPS.FACULTY[Факультет],GROUPS.PROFESSION[Специальность],PROGRESS.SUBJECT[Дисциплины], 
	   ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	   FROM GROUPS INNER JOIN FACULTY ON 
	   GROUPS.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION 
	   INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
	   INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
	   WHERE GROUPS.FACULTY IN ('ИДиП')
	   GROUP BY GROUPS.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT
	   UNION
SELECT GROUPS.FACULTY[Факультет],GROUPS.PROFESSION[Специальность],PROGRESS.SUBJECT[Дисциплины], 
	   ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	   FROM GROUPS INNER JOIN FACULTY ON 
	   GROUPS.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION 
	   INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
	   INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
	   WHERE GROUPS.FACULTY IN ('ХТиТ')
	   GROUP BY GROUPS.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT;



SELECT GROUPS.FACULTY[Факультет],GROUPS.PROFESSION[Специальность],PROGRESS.SUBJECT[Дисциплины], 
	   ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	   FROM GROUPS INNER JOIN FACULTY ON 
	   GROUPS.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION 
	   INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
	   INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
	   WHERE GROUPS.FACULTY IN ('ИДиП')
	   GROUP BY GROUPS.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT
	   INTERSECT -- НИЧЕГО НЕ ВЫВЕДЕТ Т.К. РАЗНЫЕ ФАКУЛЬТЕТЫ.
SELECT GROUPS.FACULTY[Факультет],GROUPS.PROFESSION[Специальность],PROGRESS.SUBJECT[Дисциплины], 
	   ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	   FROM GROUPS INNER JOIN FACULTY ON 
	   GROUPS.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION 
	   INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
	   INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT

	   WHERE GROUPS.FACULTY IN ('ХТиТ') 
	   GROUP BY GROUPS.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT;



SELECT GROUPS.FACULTY[Факультет],GROUPS.PROFESSION[Специальность],PROGRESS.SUBJECT[Дисциплины], 
	   ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	   FROM GROUPS INNER JOIN FACULTY ON 
	   GROUPS.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION 
	   INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
	   INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
	   WHERE GROUPS.FACULTY IN ('ИДиП')
	   GROUP BY GROUPS.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT
	   EXCEPT 
SELECT GROUPS.FACULTY[Факультет],GROUPS.PROFESSION[Специальность],PROGRESS.SUBJECT[Дисциплины], 
	   ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	   FROM GROUPS INNER JOIN FACULTY ON 
	   GROUPS.FACULTY = FACULTY.FACULTY INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION 
	   INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
	   INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
	   WHERE GROUPS.FACULTY IN ('ХТиТ') 
	   GROUP BY GROUPS.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT;



SELECT PROGRESS.SUBJECT[Дисциплины], PROGRESS.NOTE, 
	   (SELECT COUNT(*) FROM PROGRESS p2 
	    WHERE p2.SUBJECT = PROGRESS.SUBJECT AND
		p2.NOTE = PROGRESS.NOTE) FROM PROGRESS 
		GROUP BY PROGRESS.SUBJECT, PROGRESS.NOTE
		HAVING PROGRESS.NOTE BETWEEN 8 AND 9;



SELECT (SELECT COUNT(*) FROM STUDENT)[Всего в универе],
	   (SELECT COUNT(*) FROM STUDENT s3 INNER JOIN GROUPS g3 ON s3.IDGROUP = g3.IDGROUP INNER JOIN FACULTY f3 ON f3.FACULTY = g3.FACULTY 
	   WHERE f3.FACULTY = FACULTY.FACULTY)[Кол-во на каждом факультете],
	   FACULTY.FACULTY[ФАКультет],
	   (SELECT COUNT(*) FROM STUDENT s2 WHERE s2.IDGROUP = STUDENT.IDGROUP)[Кол-во в группе], STUDENT.IDGROUP
	   FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP INNER JOIN FACULTY ON FACULTY.FACULTY = GROUPS.FACULTY
	   GROUP BY FACULTY.FACULTY, STUDENT.IDGROUP;

SELECT AUDITORIUM.AUDITORIUM_TYPE[Тип аудитории],
	   (SELECT COUNT(*) FROM AUDITORIUM a4 WHERE a4.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE)[Кол-во ауд. по типу],
	   (SELECT COUNT(*) FROM AUDITORIUM)
	   FROM AUDITORIUM
	   GROUP BY AUDITORIUM.AUDITORIUM_TYPE


